### ISSUE TITLE
What are the differences between this and HenningM's library?

### ISSUE THREAD

**Issue by PCOffline** [wll8/express-ws#2]
Hey, I've stumbled across your lib and it looks promising, but can I know what are the advantages, and the differences between the two libraries?

**Comment by wll8** [comment]
I feel like it might seem rude to compare with others right now.

At present, in addition to the functional differences described in the document, it is more meaningful that other libraries have not been active for a long time, and there may be problems that cannot be solved.

**Comment by PCOffline** [comment]
Right, but I meant what issues were actually solved, and would migrating from the original express-ws would cause any issues? Besides I don't see any document that describes the differences.

**Comment by wll8** [comment]
I think you provided me with a great guide, thank you so much.

Now I have supplemented the [readme](https://github.com/wll8/express-ws/commit/bb4e4fb285f0af8ea8917b96037d987dda0955cb).
